info:
  app:
    version: @project.version@

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.flywaydb: debug

parser:
  locations: ${LINKEDIN_LOCATIONS}
  english-locations: ${ENGLISH_LOCATIONS}

  java-keywords: ${JAVA_KEYWORDS}
  big-tech-keywords: ${BIG_TECH_KEYWORDS}

  f-tpr: ${LINKEDIN_F_TPR}
  f-wt: ${LINKEDIN_F_WT}

  big-tech-companies: ${BIG_TECH_COMPANIES}
  excluded-languages: ${EXCLUDED_LANGUAGES}
  excluded-title-words: ${EXCLUDED_TITLE_WORDS}

  interval: ${PARSER_INTERVAL}
  max-years-experience: ${PARSER_MAX_YEARS_EXPERIENCE:4}

  search-delay-min-ms: ${SEARCH_DELAY_MIN_MS:3000}
  search-delay-max-ms: ${SEARCH_DELAY_MAX_MS:7000}
  job-delay-min-ms: ${JOB_DELAY_MIN_MS:1000}
  job-delay-max-ms: ${JOB_DELAY_MAX_MS:3000}

openai:
  api-key: ${OPENAI_API_KEY}
  url: ${OPENAI_URL:https://api.openai.com/v1/responses}
  model: ${OPENAI_MODEL:gpt-4.1-mini}
  enabled: ${OPENAI_ENABLED:true}
  timeout-ms: ${OPENAI_TIMEOUT_MS:10000}
  max-tokens: ${OPENAI_MAX_TOKENS:500}
  cover-letter-threshold: ${OPENAI_COVER_LETTER_THRESHOLD:70}
  prompt-path: classpath:prompts/job-fit.txt

candidate:
  profile: ${CANDIDATE_PROFILE}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}
  enabled: ${TELEGRAM_ENABLED}
  cover-letter-threshold: ${OPENAI_COVER_LETTER_THRESHOLD}